FROM balenalib/%%RESIN_MACHINE_NAME%%-debian:stretch-build

RUN apt-get update && apt-get install -yq --no-install-recommends cron

WORKDIR /opt

COPY . /opt
COPY cron-every-minute /etc/cron.d/

CMD ["/opt/loop.sh"]
